# Generated by Django 4.0.4 on 2022-05-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0003_tag_alter_news_options_alter_news_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to='news'),
        ),
    ]
