# Generated by Django 4.0.4 on 2022-05-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0005_directory_remove_news_image_news_direc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='direc',
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to='news'),
        ),
        migrations.DeleteModel(
            name='Directory',
        ),
    ]
